arc_doh/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cohort/', include('cohort.urls')),
#     url(r'^policy/', include('policy.urls')),
    url(r'^clustering/', include('clustering.urls')),
    url(r'^data_import/', include('data_import.urls')),
    url(r'^represent/', include('feature_representation.urls')),
    url(r'^metric/', include('metric.urls')),
    url(r'^visualization/', include('visualization.urls')),
    
]

cohort/urls.py
'''
Created on 3 Nov 2017

@author: xuepeng
'''

from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload', views.upload_file, name='upload_file'),
]

data_import/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import upload
from .views import renew

urlpatterns = [
    url(r'^$', upload, name='list'),
    url(r'^upload/$', upload, name='list'),
    url(r'^renew/$', renew, name='renew')
]

iml_cohort/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('data_import.urls')),
#     url(r'^cohort/', include('cohort.urls')),
    url(r'^clustering/', include('clustering.urls')),
    url(r'^data_import/', include('data_import.urls')),
    url(r'^represent/', include('feature_representation.urls')),
    url(r'^metric/', include('metric.urls')),
    url(r'^visualization/', include('visualization.urls')),
    
]

data_import/models.py
# -*- coding: utf-8 -*-
# from django.db import models

# 
# class Document(models.Model):
#     docfile = models.FileField(upload_to='documents/%Y/%m/%d')

data_import/forms.py
# -*- coding: utf-8 -*-

from django import forms


class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file'
    )

data_import/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import numpy as np

# from .models import Document 
from .forms import DocumentForm
import pandas as pd
import os
import shutil
from scipy import sparse, io


file_upload_dir = os.path.join(settings.BASE_DIR, 'data')
fs = FileSystemStorage(location=file_upload_dir)


def handle_uploaded_file(f):
    features=pd.read_csv(f,nrows=1)
    return features

#accept the file, process it and store it locally in csv format
def process_file(f,new_features):
    diag_dict = pd.read_csv(os.path.join(settings.BASE_DIR, 'data/D_ICD_DIAGNOSES.csv'))
    doc = pd.read_csv(f)
    new_doc = doc[new_features]
    distinct_dias = new_doc.DIAGNOSES_CODE.unique()
    distinct_pates = new_doc.PATIENT_ID.unique()
    diags = []
    diags_desc = []
    data = []
    diaList = distinct_dias.tolist()
    for p in distinct_pates:
        #print p
        vec = np.zeros(len(distinct_dias),dtype=int)
        ps = new_doc[new_doc['PATIENT_ID']==p]
        str_diags_codes = '\t'.join([str(code) for code in ps.DIAGNOSES_CODE])
        descs = []
        for code in ps.DIAGNOSES_CODE:
            index = diaList.index(code)
            vec[index] += 1
            desc = diag_dict[diag_dict['ICD9_CODE']==code].SHORT_TITLE
            if (not desc.empty):
                descs.append(desc.iloc[0])
            
        str_diags_desc = '\t'.join(descs)
        diags_desc.append(str_diags_desc)
        data.append(vec)
        diags.append(str_diags_codes)
        
    sparse_data = sparse.csr_matrix(data)

    file_path_data = os.path.join(settings.BASE_DIR, 'data/outcome_data')
    file_path_pationid = os.path.join(settings.BASE_DIR, 'data/outcome_pation.csv')
    file_path_deid = os.path.join(settings.BASE_DIR, 'data/outcome_deid.csv')
    file_path_diags = os.path.join(settings.BASE_DIR, 'data/outcome_diags.csv')
    file_path_diags_desc = os.path.join(settings.BASE_DIR, 'data/outcome_diags_desc.csv')

#     new_data = pd.DataFrame(data)
    distinct_dias_data = pd.DataFrame(distinct_dias)
    distinct_pates_data = pd.DataFrame(distinct_pates)
     
    #newm = io.mmread(file)
    io.mmwrite(file_path_data, sparse_data)
    distinct_dias_data.to_csv(file_path_deid,header=False)
    distinct_pates_data.to_csv(file_path_pationid,header=False)
    pd.DataFrame(data=diags,columns=['diags']).to_csv(file_path_diags)
    pd.DataFrame(data=diags_desc,columns=['diags']).to_csv(file_path_diags_desc)


def renew(request):
    if request.method == 'POST':
        new_features = request.POST.getlist('new_features')
        file_path = os.path.join(settings.BASE_DIR, 'tmp/tmp.csv')
        process_file(file_path,new_features)
        content = {'Title': "Step 3: Feature Processing",
                   "listId":"li3",
                   'features': new_features} 
        return render(
            request,
            'data_import/stp3-fea-processing.html',
            content
        )
def index(request):
    content = {'Title': "Step 1: Upload Data",
                   "listId":"li1"}    
    return render(request, 'data_import/stp1-import.html', content)
    

def upload(request):
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            print "request files in list-----",request.FILES
            docfile = request.FILES['docfile']
            features = handle_uploaded_file(docfile)
            file_upload_dir = os.path.join(settings.BASE_DIR, 'tmp')
            fs = FileSystemStorage(location=file_upload_dir)
            if os.path.exists(file_upload_dir): 
                shutil.rmtree(file_upload_dir)
            fs.save("tmp.csv", docfile)
            
            content = {'Title': "Step 2: Feature Selection",
                   "listId":"li2",
                   'features': features} 
            return render(
                request,
                'data_import/stp2-fea-selection.html',
                content
            )

    else:
        content = {'Title': "Step 1: Upload Data",
                   "listId":"li1"}    
        return render(request, 'data_import/stp1-import.html', content)

data_import/templates/data_import/stp1-import.html
{% include "header.html"%}

<main role="main">
<!-- here for upload file content -->
	<div class="page-content">
		<div class="row" style="padding:5px; width:98%;">
			<div id="home" class="tab-pane fade in active clear" style="text-align:center; padding:80px;">
			   <h2>Select file to upload <br/>
			   	<small>Maximum upload size is 3mb.<br>
			   	</small>
			   </h2>
			   <br/>
			   <form class="form-inline" style="padding:10px;" role="form" action="{% url "list" %}" method="post" enctype="multipart/form-data">
         					{% csrf_token %}
			   		<input style="padding:0px;" class="form-control" type="file" name="docfile" required id="id_docfile"><br/><br/>
			   		<input type="submit" class="btn btn-primary" value="Upload">
			   </form>
			</div>		
		</div>
	</div>
</main>

  
{% include "footer.html"%}

data_import/templates/data_import/stp2-fea-selection.html
{% include "header.html"%}

<main role="main">
<!-- here for upload file content -->
	<div class="page-content container">
		<form action="{% url "renew" %}" method="post" enctype="multipart/form-data" 
		class="form-horizontal  center-block" style="width: 30%;text-align:center">
		{% csrf_token %}
			<div class="form-group">
						   <h2>Select required features <br/>
						   </h2>				
				<span id="helpBlock-example" class="help-block">Hold down the Ctrl (windows) / Command (Mac) button to select multiple options.</span>
				<select name="new_features" multiple class="form-control" style="min-height: 200px;">
 
			      {% for f in features %}
				      <option value="{{f}}">{{f}}</option>
				  {% endfor %}
			 
			</select>
			
			<input type="submit" class="btn btn-primary" value="Select" style="margin-top: 15px;">
			</div>
		</form>
	</div>
</main>

  {% include "footer.html"%}

data_import/templates/data_import/stp3-fea-processing.html
{% include "header.html"%}

<main role="main">
<!-- here for upload file content -->
	<div class="page-content container" style="padding-top: 25px;">
		
		<div class="row">
<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
		            <tr>
		                <th>Feature Name</th>
		                <th>Data Type</th>
		                <th>Process </th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Feature Name</th>
		                <th>Data Type</th>
		                <th>Process</th>
		            </tr>
		        </tfoot>
		        <tbody>
					<tr>
					  <td>SUBJECT_ID</td>
					  <td>String</td>
					  <td>One-Hot</td>
					</tr>
					<tr>
					  <td>ICD9_CODE</td>
					  <td>String</td>
					  <td>One-Hot</td>
					</tr>
		            
		        </tbody>
    </table>		
		</div>
		<div class="row" id="button-div2">
			<button class="btn btn-primary center-block" type="button" onclick="window.location.href='/represent'">Next Step</button>
		</div>		
	</div>
</main>

{% include "footer.html"%}